name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: any

  # other dependencies
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  path: ^1.8.3
  provider: ^6.1.5
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
